name: artifacts

on:
  push:

jobs:
  donwload-artifacts:
    needs: upload-artifacts
    name: job to download & test the artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R
      - run: cat myArtifact.txt
  
  upload-artifacts:
    name: job to upload the artifacts
    runs-on: ubuntu-latest
    steps:
      - run: docker info >myArtifact.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: myArtifact.txt
